---
- name: New SNOW incident
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create an incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "Update of Network Device Complete"
          description: "Router config has been updated on rtr3 "
          severity: 4
          priority: 2 
          assigned_to: vsylvest
      register: net-pass