---
- name: SNOW Incident
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Test Network Configuration Change Completed
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "Network Changes on IOS Router has completed"
          description: "production is ready for changes"
          severity: 4
          priority: 2 
          assigned_to: vsylvest
      register: net-pass